apiVersion: apps/v1
kind: Deployment
metadata:
  name: "dev-{{ .Release.Name }}-back"
  labels:
    app: "dev-{{ .Release.Name }}-back"
  annotations:
    timestamp: {{ now | quote }}
spec:
  replicas: {{ .Values.back.replicas }}
  selector:
    matchLabels:
      app: "dev-{{ .Release.Name }}-back"
  template:
    metadata:
      labels:
        app: "dev-{{ .Release.Name }}-back"
    spec:
      containers:
        - name: "dev-{{ .Release.Name }}-back"
          imagePullPolicy: "{{ .Values.back.pullPolicy }}"
          image: "{{ .Values.container.repository }}/{{ .Values.back.image }}:{{ .Values.back.tag }}"
          command: ["/bin/bash", "-c", "pnpm start:www"]
          ports:
            - containerPort: {{ .Values.back.port }}
              protocol: TCP
          resources:
            requests:
              cpu: "{{ .Values.back.resources.requests.cpu }}"
              memory: "{{ .Values.back.resources.requests.memory }}"
            limits:
              cpu: "{{ .Values.back.resources.limits.cpu }}"
              memory: "{{ .Values.back.resources.limits.memory }}"
          envFrom:
            - configMapRef:
                name: "dev-{{ .Release.Name }}-back-config"
          volumeMounts:
            - name: "dev-{{ .Release.Name }}-back-config-file"
              mountPath: "/app/"
              readOnly: true
              subPath: ".env"
      volumes:
        - name: "dev-{{ .Release.Name }}-back-config-file"
          configMap:
            name: "dev-{{ .Release.Name }}-back-config"