apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "dev-{{ .Release.Name }}-back-hpa"
  labels:
    app: "dev-{{ .Release.Name }}-back"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "dev-{{ .Release.Name }}-back"
  minReplicas: {{ .Values.back.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.back.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.back.autoscaling.cpuTarget }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.back.autoscaling.memoryTarget }}