# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: "dev-{{ .Release.Name }}-back-hpa"
#   labels:
#     app: "dev-{{ .Release.Name }}-back"
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: "dev-{{ .Release.Name }}-back"
#   minReplicas: {{ .Values.back.autoscaling.minReplicas }}
#   maxReplicas: {{ .Values.back.autoscaling.maxReplicas }}
#   metrics:
#     - type: Pods
#       pods:
#         metric:
#           name: cpu_usage_seconds_total 
#         target:
#           type: AverageValue
#           averageValue: "{{ .Values.back.autoscaling.cpuTarget }}"
#     - type: Pods
#       pods:
#         metric:
#           name: memory_usage_bytes
#         target:
#           type: AverageValue
#           averageValue: "{{ .Values.back.autoscaling.memoryTarget }}"