apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5VENDQWQyZ0F3SUJBZ0lSQUlXaWdkTnlQRU5oaWM3REVWYlU2RlF3RFFZSktvWklodmNOQVFFTEJRQXcKSWpFZ01CNEdBMVVFQXd3WGEzVmlaWEp1WlhSbGN5MWpiSFZ6ZEdWeUxUY3lOVE13SGhjTk1qVXdOekExTWpNMQpOekV5V2hjTk16QXdOekExTWpNMU56RXlXakFpTVNBd0hnWURWUVFEREJkcmRXSmxjbTVsZEdWekxXTnNkWE4wClpYSXROekkxTXpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTkNOY1RjK1A2V0QKZFFMMDJxYWluZXhhcjR6RnZwdVdYeWlTMFk5TnBqM05SbXNzRVBXOGNEYlVRdWphV3NWQllKY2N4czA3TGtpSgpvYksvaythbXN5UWpaZ1hKcGNBQ1hZcHU4eS9iQU8wL2Nva3BOcDYvZlRGT0lNSlkyYlQyMCtzRTVFc2RCWTl2CmlnRDNSaUYzcmVwSG9CdC9CU1FERFV2NzlBekJ3QUwvS0tVSXJUenpLd3NPODRleGdVRklRVWUvUEs0T09YdysKRllWR20ySlY5NGJqVDhsZU0rRDZLQ2JFcS8yODAzSnhodnB4SVRJcFYxSmdVME0vcUN5d1B1emdHSmtZR2MvcQp4bGtCTTRYQVl5a2hwSnFmMXFhMGxYbFdaMWpCTll0bGVDSGt6bFUra2VPYkdqenV4VmdWS2FXdUFIdGE4YzV4CkpuK21tdGFMa2xjQ0F3RUFBYU1tTUNRd0VnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFEQU9CZ05WSFE4QkFmOEUKQkFNQ0FnUXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBR21QcHN6V3p5RnFiN2pNa3lhZDFQNE1uSE5xcm5wdApzS1VnMFRSa0NEUDJkNWpPcThyeEoxTldHMzRmNjZxV3BaQ002bjRERHdrb0xMcldKT1hRUmdOQUtyMUtPQmxzCkxhUnp3Yi9mREtGMjc0OTM5RXVNMjU3NkF1N1pPYmREeFptNUNtREo3a0ZSbGtoV3ZKRlVVZU9uYUMwbm9DTlUKSkhwRWk2TmZMM21tak56K0hjRk1FeU1RRlZFMTEvMzJTblAzQmVyU1ZoZzhIUnIyVWxOVzdFbGNSSXhVUlJGSwpvRElaSU01R3l4VGdEcGpLTnFoa0lud2ZNblNtQ1hGZUs4RkFhdS9sZlJ4OFoyVmhUeEFCZW9ucUFkb2ZoQjFHCkxVVnpVNis1bDBSd1hKVTQ0ZTVPLzdIczZ0ck84T3lIcUxUNXhLZFFUYUZZWFhSSDJIYmNVVDg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://109.120.182.129:6443
  name: kubernetes-cluster-7253
contexts:
- context:
    cluster: kubernetes-cluster-7253
    user: kubernetes-cluster-7253
  name: default/kubernetes-cluster-7253
current-context: default/kubernetes-cluster-7253
kind: Config
preferences: {}
users:
- name: kubernetes-cluster-7253
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: client-keystone-auth
      env:
      - name: "OS_AUTH_URL"
        value: "https://infra.mail.ru:35357/v3/"
      - name: "OS_USERNAME"
        value: "mr.muraveiko@gmail.com"
      - name: "OS_PASSWORD"
        value: "Iamtired404!"
      - name: "OS_PROJECT_ID"
        value: "875deb6eb9344e5ea2603b95465af314"
      - name: "OS_DOMAIN_NAME"
        value: "users"
      interactiveMode: IfAvailable
      provideClusterInfo: false