apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-volume-claim
  labels:
    app: redis
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""