apiVersion: v1
kind: ConfigMap

metadata:
  name: "dev-{{ .Release.Name }}-back-config"
  labels:
    app: "dev-{{ .Release.Name }}-back-config"

data:
  NODE_ENV: production

  HOSTNAME: https://{{ .Values.hostname }}
  PORT: "4000"

  BOT_API_KEY: "8027260157:AAEfw3gM7Hgd4OOrj_3lUOB6xIEydWmSAI4"

  TON_ADDRESS: "UQDXtkcZ4G5-SuPKLMNHE5ki7TTKufQkq1jSRUfZB1AJR1kT"
  TON_MNEMONIC: ""

  TON_API_KEY: "AESRQ2TFWYGQVXIAAAANMNGLBVAJ4IFLQOR7BQMN2P3LNAEWR7X6XM3INBEFPBJD4MC47MI"
  TON_CENTER_API_KEY: "be351acde3a088630eea2753fd3f61771c0c96c4e16d6a8973cbae84fd3ef7fd"
  CRYPTO_COMPARE_API_KEY: "41b87d7ebb1b3df45e7cdcad09707425a8a1792cb4a55bb3a7cf763cb3a60788"

  DATABASE_URL: "postgres://user:AF63+64XLB5H4J86x@212.233.90.225/production"
  SHADOW_DATABASE_URL: "postgres://user:AF63+64XLB5H4J86x@212.233.90.225/prisma_shadow"

  REDIS_DOMAIN: redis-cache-redis
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "1"
  REDIS_USERNAME: "default"

  PORTAL_API_KEY: "eda29b65-7f66-4c52-8712-d617399d2b60"