apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "dev-{{ .Release.Name }}-ingress"
  labels:
    app: "dev-{{ .Release.Name }}-ingress"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - {{ .Values.hostname }}
      secretName: dev-tls
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: "dev-{{ .Release.Name }}-back"
                port:
                  number: {{ .Values.back.port }}