apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ .Release.Name }}-ingressroute-app"
  labels:
    app: "{{ .Release.Name }}-app"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.hostname }}`) && PathPrefix(`/`) && Headers(`Upgrade`, `websocket`)
      kind: Rule
      services:
        - name: "dev-{{ .Release.Name }}-back-ws"
          port: {{ .Values.back.port }}
      timeouts:
        idleTimeout: 3600s
    - match: Host(`{{ .Values.hostname }}`) && PathPrefix(`/go`)
      kind: Rule
      services:
        - name: "dev-{{ .Release.Name }}-back"
          port: {{ .Values.back.port }}
      middlewares:
        - name: "{{ .Release.Name }}-strip-api"
    - match: Host(`{{ .Values.hostname }}`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: "dev-{{ .Release.Name }}-front"
          port: {{ .Values.front.port }}
  tls:
    secretName: dev-tls