apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ .Release.Name }}-ingressroute-app"
  labels:
    app: "{{ .Release.Name }}-app"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.hostname }}`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: "dev-{{ .Release.Name }}-back"
          port: {{ .Values.back.port }}
      middlewares:
        - name: "{{ .Release.Name }}-strip-api"
  tls:
    secretName: dev-tls